# Generated by Django 3.0.5 on 2020-06-14 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
